sudo: true
language: php
php:
- 7.1.11
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
  - "$HOME/.composer/cache/files/"
  - node_modules
  - vendor
before_install:
- openssl aes-256-cbc -K $encrypted_100c514c8090_key -iv $encrypted_100c514c8090_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- phpenv config-rm xdebug.ini
- if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash;
  fi
- tar -xzf credentials.tar.gz
- composer self-update
- composer install --no-interaction
script:
- echo "No Script to run"
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret-travis.json
  project: horcholle
  default: true
  on: master
