sudo: true
language: php
php:
- 7.1.11
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
  - "$HOME/.composer/cache/files/"
  - node_modules
  - vendor
before_install:
- openssl aes-256-cbc -K $encrypted_100c514c8090_key -iv $encrypted_100c514c8090_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- phpenv config-rm xdebug.ini
- if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash; fi
- tar -xzf credentials.tar.gz
- echo "Authenticate with gcloud";
- gcloud auth activate-service-account --key-file secrets/travis-cloud-sql-access.json;
- composer self-update
- composer install --no-interaction
- wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O ${HOME}/google-cloud-sdk/cloud_sql_proxy
- chmod +x ${HOME}/google-cloud-sdk/cloud_sql_proxy
- "${HOME}/google-cloud-sdk/cloud_sql_proxy -instances=horcholle:europe-west1:horcholle-instance-prod=tcp:3307"
script:
- vendor/bin/phpunit
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: secrets/travis-build-access.json
  project: horcholle
  default: true
  on: master
